server {
    listen 80;
	location = / {
		return 301 /help/;
	}
    location /help/ {
        alias /usr/share/nginx/html/;
        index index.html;
    }
    location /help {
        return 301 /help/;
    }
}

