#!/bin/bash
# env-setup.sh
# Creates the .env file used by docker-compose.yml.
# Prompts for No-IP DDNS credentials and writes them to ./.env.
#
# Usage:
#   ./env-setup.sh
#
# Safe to re-run; will ask before overwriting an existing .env.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [ -f "$ENV_FILE" ]; then
    read -r -p ".env already exists at ${ENV_FILE}. Overwrite? [y/N] " confirm
    case "$confirm" in
        [yY]|[yY][eE][sS]) ;;
        *) echo "Aborted. Existing .env left untouched."; exit 0 ;;
    esac
fi

echo "Setting up No-IP DDNS credentials."
echo "Output: ${ENV_FILE}"
echo

# --- NOIP_NAME --------------------------------------------------------------
# The DDNS hostname prefix, e.g. 'myserver' for 'myserver.ddns.net'.
# Stored for reference (e.g. building published URLs); not consumed directly
# by the noip-duc container.
read -r -p "DDNS hostname (the part BEFORE '.ddns.net', e.g. 'myserver'): " NOIP_NAME
while [ -z "${NOIP_NAME}" ]; do
    read -r -p "  Hostname cannot be empty. Try again: " NOIP_NAME
done

# --- NOIP_USERNAME ----------------------------------------------------------
# The DDNS Key username from your No-IP account (NOT your No-IP login email).
read -r -p "DDNS Key username: " NOIP_USERNAME
while [ -z "${NOIP_USERNAME}" ]; do
    read -r -p "  Username cannot be empty. Try again: " NOIP_USERNAME
done

# --- NOIP_PASSWORD ----------------------------------------------------------
# The DDNS Key password. Read silently.
while :; do
    read -r -s -p "DDNS Key password: " NOIP_PASSWORD
    echo
    if [ -n "${NOIP_PASSWORD}" ]; then
        break
    fi
    echo "  Password cannot be empty."
done

# --- NOIP_HOSTNAMES ---------------------------------------------------------
# 'all.ddnskey.com' is a No-IP wildcard token that tells the DUC to update
# every hostname associated with the DDNS key. This avoids needing to update
# .env if you add hostnames to your No-IP account later.
NOIP_HOSTNAMES="all.ddnskey.com"

# --- Write .env -------------------------------------------------------------
umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by env-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT. .env is excluded by .gitignore.

# No-IP DDNS configuration (consumed by docker-compose.yml -> noip-duc)
NOIP_NAME=${NOIP_NAME}
NOIP_USERNAME=${NOIP_USERNAME}
NOIP_PASSWORD=${NOIP_PASSWORD}
NOIP_HOSTNAMES=${NOIP_HOSTNAMES}
EOF

chmod 600 "${ENV_FILE}"

echo
echo "Wrote ${ENV_FILE} (mode 600)."
echo "Public URL will be: https://${NOIP_NAME}.ddns.net"
