#!/bin/bash
# render-dnsmasq-config.sh
# Renders dnsmasq/conf.d/local.conf from values in .env.
# Re-run any time NOIP_NAME or LOCAL_IP change in .env.
#
# Usage:
#   ./render-dnsmasq-config.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
DNSMASQ_CONF_DIR="${SCRIPT_DIR}/dnsmasq/conf.d"
DNSMASQ_CONF_FILE="${DNSMASQ_CONF_DIR}/local.conf"

if [ ! -f "${ENV_FILE}" ]; then
    echo "Error: ${ENV_FILE} not found. Run env-setup.sh first." >&2
    exit 1
fi

# Load .env into this script's environment.
# 'set -a' auto-exports each assignment; we toggle it off after sourcing.
set -a
# shellcheck disable=SC1090
. "${ENV_FILE}"
set +a

: "${NOIP_NAME:?NOIP_NAME is not set in ${ENV_FILE}}"
: "${LOCAL_IP:?LOCAL_IP is not set in ${ENV_FILE}}"

mkdir -p "${DNSMASQ_CONF_DIR}"
umask 022
cat > "${DNSMASQ_CONF_FILE}" <<EOF
# Generated by render-dnsmasq-config.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run render-dnsmasq-config.sh after changing NOIP_NAME or LOCAL_IP in .env.
address=/${NOIP_NAME}.ddns.net/${LOCAL_IP}
EOF

echo "Wrote ${DNSMASQ_CONF_FILE}"
echo "  ${NOIP_NAME}.ddns.net -> ${LOCAL_IP}"
